'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor", IsNullable:=false)>  _
Partial Public Class MensajeReceptor
    
    Private claveField As String
    
    Private numeroCedulaEmisorField As String
    
    Private fechaEmisionDocField As Date
    
    Private mensajeField As MensajeReceptorMensaje
    
    Private detalleMensajeField As String
    
    Private montoTotalImpuestoField As Decimal
    
    Private montoTotalImpuestoFieldSpecified As Boolean
    
    Private totalFacturaField As Decimal
    
    Private numeroCedulaReceptorField As String
    
    Private numeroConsecutivoReceptorField As String
    
    '''<remarks/>
    Public Property Clave() As String
        Get
            Return Me.claveField
        End Get
        Set
            Me.claveField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NumeroCedulaEmisor() As String
        Get
            Return Me.numeroCedulaEmisorField
        End Get
        Set
            Me.numeroCedulaEmisorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property FechaEmisionDoc() As Date
        Get
            Return Me.fechaEmisionDocField
        End Get
        Set
            Me.fechaEmisionDocField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property Mensaje() As MensajeReceptorMensaje
        Get
            Return Me.mensajeField
        End Get
        Set
            Me.mensajeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property DetalleMensaje() As String
        Get
            Return Me.detalleMensajeField
        End Get
        Set
            Me.detalleMensajeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property MontoTotalImpuesto() As Decimal
        Get
            Return Me.montoTotalImpuestoField
        End Get
        Set
            Me.montoTotalImpuestoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property MontoTotalImpuestoSpecified() As Boolean
        Get
            Return Me.montoTotalImpuestoFieldSpecified
        End Get
        Set
            Me.montoTotalImpuestoFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TotalFactura() As Decimal
        Get
            Return Me.totalFacturaField
        End Get
        Set
            Me.totalFacturaField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NumeroCedulaReceptor() As String
        Get
            Return Me.numeroCedulaReceptorField
        End Get
        Set
            Me.numeroCedulaReceptorField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property NumeroConsecutivoReceptor() As String
        Get
            Return Me.numeroConsecutivoReceptorField
        End Get
        Set
            Me.numeroConsecutivoReceptorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor")>  _
Public Enum MensajeReceptorMensaje
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("1")>  _
    Item1
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("2")>  _
    Item2
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("3")>  _
    Item3
End Enum
